book:
	raco pollen reset; raco pollen render book.ltx; raco pollen render book.pdf

site:
	raco pollen reset; raco pollen render index.html; raco pollen render -t html abbreviations.poly.pm appendix-1.poly.pm appendix-2.poly.pm bibliography.poly.pm chapter-1.poly.pm chapter-2.poly.pm chapter-3.poly.pm chapter-4.poly.pm chapter-5.poly.pm chapter-6.poly.pm conclusion.poly.pm introduction.poly.pm preface.poly.pm
